# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir mcp[cli]==1.5.0 requests python-dotenv

# Copy application code
COPY . /app

# Expose nothing; stdio
# Command
CMD ["python", "server.py"]
